package com.autom8ed.fibersocial.auth

import io.ktor.http.URLBuilder
import io.ktor.http.takeFrom

/**
 * Builds the Ravelry OAuth 2.0 authorization URL (PKCE, `S256`) and holds the verifier
 * generated for it until [consumeCodeVerifier] retrieves it for the token exchange.
 */
class RavelryAuthManager {

    companion object {
        const val REDIRECT_URI = "fibersocial://auth/callback"
        private const val AUTH_URL = "https://www.ravelry.com/oauth2/auth"

        // Ravelry grants a read-only token when no scope is requested, which 403s every
        // write (reply/edit/delete). `forum-write` grants forum posting; `message-write`
        // grants posting project comments (issue #103 — its Ravelry description mentions
        // private messages, but comments/create requires it too); `offline` is required
        // to receive a refresh token (without it Ravelry often omits one, forcing frequent
        // re-login). Space-separated per the OAuth spec. Tokens issued before a scope was
        // added lack it until the user next logs in, so new-scope writes 403 for them.
        const val SCOPE = "forum-write message-write offline"
    }

    private var codeVerifier: String? = null
    private var state: String? = null

    fun buildAuthUrl(clientId: String): String {
        val verifier = generateCodeVerifier().also { codeVerifier = it }
        val challenge = generateCodeChallenge(verifier)
        val stateVal = generateState().also { state = it }
        return URLBuilder().apply {
            takeFrom(AUTH_URL)
            parameters.append("response_type", "code")
            parameters.append("client_id", clientId)
            parameters.append("redirect_uri", REDIRECT_URI)
            parameters.append("code_challenge", challenge)
            parameters.append("code_challenge_method", "S256")
            parameters.append("state", stateVal)
            parameters.append("scope", SCOPE)
        }.buildString()
    }

    /** Returns the verifier generated by the most recent [buildAuthUrl] call, consuming it. */
    fun consumeCodeVerifier(): String =
        codeVerifier?.also { codeVerifier = null } ?: error("No code verifier — call buildAuthUrl first")

    /**
     * Checks the `state` returned on the OAuth redirect against the one issued by the most
     * recent [buildAuthUrl] call, consuming it (one-time use). Returns `true` only on an
     * exact match — a mismatch, a missing returned value, or no issued state (a second call,
     * or a redirect that arrives before any auth URL was built) all return `false`.
     *
     * This is the login-CSRF defense: without it, an attacker could trick a user into
     * completing an auth flow the attacker initiated. Callers must reject the auth code
     * when this returns `false` (issue #149).
     */
    fun validateState(returnedState: String?): Boolean {
        val expected = state
        state = null
        return expected != null && expected == returnedState
    }

    private fun generateState(): String = base64UrlEncode(secureRandomBytes(16))

    private fun generateCodeVerifier(): String = base64UrlEncode(secureRandomBytes(32))

    private fun generateCodeChallenge(verifier: String): String =
        base64UrlEncode(sha256(verifier.encodeToByteArray()))
}
