package com.autom8ed.fibersocial.auth

import io.ktor.http.URLBuilder
import io.ktor.http.takeFrom

/**
 * Builds the Ravelry OAuth 2.0 authorization URL (PKCE, `S256`) and holds the verifier
 * generated for it until [consumeCodeVerifier] retrieves it for the token exchange.
 */
class RavelryAuthManager {

    companion object {
        const val REDIRECT_URI = "fibersocial://auth/callback"
        private const val AUTH_URL = "https://www.ravelry.com/oauth2/auth"

        // Ravelry grants a read-only token when no scope is requested, which 403s every
        // write (reply/edit/delete). `forum-write` grants forum posting; `offline` is
        // required to receive a refresh token (without it Ravelry often omits one, forcing
        // frequent re-login). Space-separated per the OAuth spec.
        const val SCOPE = "forum-write offline"
    }

    private var codeVerifier: String? = null
    private var state: String? = null

    fun buildAuthUrl(clientId: String): String {
        val verifier = generateCodeVerifier().also { codeVerifier = it }
        val challenge = generateCodeChallenge(verifier)
        val stateVal = generateState().also { state = it }
        return URLBuilder().apply {
            takeFrom(AUTH_URL)
            parameters.append("response_type", "code")
            parameters.append("client_id", clientId)
            parameters.append("redirect_uri", REDIRECT_URI)
            parameters.append("code_challenge", challenge)
            parameters.append("code_challenge_method", "S256")
            parameters.append("state", stateVal)
            parameters.append("scope", SCOPE)
        }.buildString()
    }

    /** Returns the verifier generated by the most recent [buildAuthUrl] call, consuming it. */
    fun consumeCodeVerifier(): String =
        codeVerifier?.also { codeVerifier = null } ?: error("No code verifier — call buildAuthUrl first")

    private fun generateState(): String = base64UrlEncode(secureRandomBytes(16))

    private fun generateCodeVerifier(): String = base64UrlEncode(secureRandomBytes(32))

    private fun generateCodeChallenge(verifier: String): String =
        base64UrlEncode(sha256(verifier.encodeToByteArray()))
}
