package com.myhobbyislearning.fibersocial.auth

import io.ktor.http.URLBuilder
import io.ktor.http.takeFrom

/**
 * Builds the Ravelry OAuth 2.0 authorization URL (PKCE, `S256`) and holds the verifier
 * generated for it until [consumeCodeVerifier] retrieves it for the token exchange.
 */
class RavelryAuthManager {

    companion object {
        const val REDIRECT_URI = "fibersocial://auth/callback"
        private const val AUTH_URL = "https://www.ravelry.com/oauth2/auth"

        // Ravelry grants a read-only token when no scope is requested, which 403s every
        // write (reply/edit/delete). `forum-write` grants forum posting; `message-write`
        // grants posting project comments (issue #103 — its Ravelry description mentions
        // private messages, but comments/create requires it too); `message-read` grants
        // READING private messages (issue #396 — see below); `offline` is required to
        // receive a refresh token (without it Ravelry often omits one, forcing frequent
        // re-login). Space-separated per the OAuth spec. Tokens issued before a scope was
        // added lack it until the user next logs in, so new-scope calls 403 for them.
        //
        // `message-read` IS APPROVAL-GATED, and this app has been approved (issue #396).
        // Do not assume any other Ravelry app can request it. Until 2026-08-06 this scope
        // was unobtainable and every route to it was live-tested closed: `/oauth2/auth`
        // rejected it as `invalid_scope`, `/oauth2/token` silently stripped it from the
        // grant, OAuth 1.0a hit the same wall, and even a token holding all seven
        // documented scopes still 403'd every message read. That is why the whole
        // messages feature was built against an API it could not yet read from, and why
        // the website-scraping fallback (#399/PR #404) was drafted. With the grant in
        // hand, requesting it here is the entire fix — do not delete it from this string
        // without re-reading #396, because the read path has no other way in.
        const val SCOPE = "forum-write message-write message-read offline"
    }

    private var codeVerifier: String? = null
    private var state: String? = null

    fun buildAuthUrl(clientId: String): String {
        val verifier = generateCodeVerifier().also { codeVerifier = it }
        val challenge = generateCodeChallenge(verifier)
        val stateVal = generateState().also { state = it }
        return URLBuilder().apply {
            takeFrom(AUTH_URL)
            parameters.append("response_type", "code")
            parameters.append("client_id", clientId)
            parameters.append("redirect_uri", REDIRECT_URI)
            parameters.append("code_challenge", challenge)
            parameters.append("code_challenge_method", "S256")
            parameters.append("state", stateVal)
            parameters.append("scope", SCOPE)
        }.buildString()
    }

    /** Returns the verifier generated by the most recent [buildAuthUrl] call, consuming it. */
    fun consumeCodeVerifier(): String =
        codeVerifier?.also { codeVerifier = null } ?: error("No code verifier — call buildAuthUrl first")

    /**
     * Checks the `state` returned on the OAuth redirect against the one issued by the most
     * recent [buildAuthUrl] call, consuming it (one-time use). Returns `true` only on an
     * exact match — a mismatch, a missing returned value, or no issued state (a second call,
     * or a redirect that arrives before any auth URL was built) all return `false`.
     *
     * This is the login-CSRF defense: without it, an attacker could trick a user into
     * completing an auth flow the attacker initiated. Callers must reject the auth code
     * when this returns `false` (issue #149).
     */
    fun validateState(returnedState: String?): Boolean {
        val expected = state
        state = null
        return expected != null && expected == returnedState
    }

    private fun generateState(): String = base64UrlEncode(secureRandomBytes(16))

    private fun generateCodeVerifier(): String = base64UrlEncode(secureRandomBytes(32))

    private fun generateCodeChallenge(verifier: String): String =
        base64UrlEncode(sha256(verifier.encodeToByteArray()))
}
